# Generated by Django 4.0.5 on 2022-07-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='info',
            field=models.CharField(max_length=2500),
        ),
    ]
