# Generated by Django 4.0.5 on 2022-07-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_book_appointment_user_pdf_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='pdf/%Y/%m/%d/'),
        ),
    ]
