# Generated by Django 4.0.5 on 2022-08-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_diagnosis_alter_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='diagnosis',
            new_name='medical_history',
        ),
    ]
