# Generated by Django 4.0.5 on 2022-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_diagnosis_user_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
